server.compression.enabled=true
server.http2.enabled: true

springdoc.packagesToScan=org.netlykos.fortune
springdoc.version=@springdoc.version@
springdoc.swagger-ui.use-root-path=true

management.endpoints.web.exposure.include=actuator,health,info,loggers,metrics,mappings
