@url = http://localhost:8080

####
GET {{url}}/api/fortune
accept: text/html

####
GET {{url}}/api/fortune
accept: text/plain

####
GET {{url}}/api/fortune
accept: application/xhtml+xml

####
GET {{url}}/api/fortune
accept: application/xml

####
GET {{url}}/api/fortune/pratchett/3 HTTP/2
accept: application/xml

####
GET {{url}}/api/fortune/pratchett/2 HTTP/2
accept: application/json

####
GET {{url}}/api/categories HTTP/2
accept: application/xml

####
GET {{url}}/api/categories HTTP/2
accept: application/json

####
GET {{url}}/api/fortune HTTP/2
accept: application/json


####
GET {{url}}/actuator

####
GET {{url}}/actuator/mappings

####
GET {{url}}/actuator/beans

