# System Properties
systemProp.file.encoding=utf-8
# jvm arguments for gradle
org.gradle.jvmargs='-Dfile.encoding=UTF-8'

# Version(s) for various artifacts used in this project
springBootVersion=3.2.+
springDocVersion=2.5.+
jakartaInjectApiVersion=2.0.1.MR
jakartaAnnotationApiVersion=3.0.0-M1

# Version for various Gradle Plugins
gradleNodePluginVersion=7.+
nebulaNodePluginVersion=4.+
nebulaGradleInfoPluginVersion=13.+
sonarqubeGradlePluginVersion=5.+
# This property should match springBootVersion
springBootGradlePluginVersion=3.2.+
springDependencyManagementPluginVersion=1.1.+

# Properties used by the sonar plugin
sonarProjectKey=netlykos_fortune
sonarOrganization=netlykos
sonarHostUrl=https://sonarcloud.io

# Verion for node and npm when used by gradle
nodeVersion=22.0.0
npmVersion=10.5.1

