plugins {
  id "org.netlykos.fortune.spring-boot-application"
}

dependencies {
  implementation project(":app:base")
  implementation project(":app:file-library")

  implementation "jakarta.annotation:jakarta.annotation-api"
  implementation "jakarta.inject:jakarta.inject-api"

  implementation "org.springframework.boot:spring-boot-starter"
  implementation "org.springframework.boot:spring-boot-starter-webflux"
  implementation "org.springframework.boot:spring-boot-starter-actuator"

  implementation "org.springdoc:springdoc-openapi-starter-webflux-ui"
  implementation "org.springdoc:springdoc-openapi-starter-webflux-api"

  testImplementation "org.springframework.boot:spring-boot-devtools"
}
