plugins {
  id "org.netlykos.fortune.spring-boot-application"
}

dependencies {
  implementation project(":app:base")
  implementation project(":app:base-web")
  implementation project(":app:file-library")
  implementation project(":app:spring-core")

  implementation "jakarta.annotation:jakarta.annotation-api"
  implementation "jakarta.inject:jakarta.inject-api"

  implementation "org.springframework.boot:spring-boot-starter"
  implementation "org.springframework.boot:spring-boot-starter-web"
  implementation "org.springframework.boot:spring-boot-starter-actuator"

  implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui"
  implementation "org.springdoc:springdoc-openapi-starter-webmvc-api"

  testImplementation "org.springframework.boot:spring-boot-devtools"
  testImplementation "org.springframework.boot:spring-boot-starter-test"
}
