@url = http://localhost:8080

GET {{url}}/api/mvc/categories
accept: application/xml


####
GET {{url}}/api/mvc/categories
accept: application/xml


####
GET {{url}}/api/mvc/fortune
accept: application/json


####
GET {{url}}/api/mvc/fortune
accept: application/xml


####
GET {{url}}/api/flux/fortune
accept: application/xml
content-type: application/xml


####
